api:
  host: localhost
  port: 8081
sqllinx:
  host: 10.58.192.51
  port: 1433
  username: ti_consulta 
  password: consulta
auth: 
  server: alfa.local
  port: 389
  basedn: DC=alfa,DC=local
  grupo : api_fiscal